// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGrIx1ZgOhNSnCTqq0iN9SmawxJnLJ0E',
    appId: '1:153396135668:android:c97aaf5c8e120bbbe900a1',
    messagingSenderId: '153396135668',
    projectId: 'procastimate-adet',
    storageBucket: 'procastimate-adet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_iQP7FzQ-VpoNegFI9udbphzGirIIshU',
    appId: '1:153396135668:ios:d30570b1c3d3b155e900a1',
    messagingSenderId: '153396135668',
    projectId: 'procastimate-adet',
    storageBucket: 'procastimate-adet.firebasestorage.app',
    iosBundleId: 'com.example.procastimateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB91AQg1TAJ1IHD1SGR_yDdIXwIkVYg5Ic',
    appId: '1:153396135668:web:bbc10f3f68aa482be900a1',
    messagingSenderId: '153396135668',
    projectId: 'procastimate-adet',
    authDomain: 'procastimate-adet.firebaseapp.com',
    storageBucket: 'procastimate-adet.firebasestorage.app',
  );

}